export const JOBS_BY_API_MOCK = [
  {
    job_id: "lo3DOye1BkhPRCYPAAAAAA==",
    employer_name: "PureCode AI",
    employer_logo: null,
    employer_website: "http://purecodesoftware.com",
    employer_company_type: null,
    job_publisher: "ZipRecruiter",
    job_employment_type: "PARTTIME",
    job_title: "React.js Developer",
    job_apply_link:
      "https://www.ziprecruiter.com/c/PureCode-AI/Job/React.js-Developer/-in-Austin,TX?jid=7004e93c657c6e50",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.5846,
    apply_options: [
      {
        publisher: "ZipRecruiter",
        apply_link:
          "https://www.ziprecruiter.com/c/PureCode-AI/Job/React.js-Developer/-in-Austin,TX?jid=7004e93c657c6e50",
        is_direct: true,
      },
    ],
    job_description:
      "PureCode AI https://purecode.ai/ , is an innovative startup based in Austin, Texas, is seeking a talented remote React Developer to join our team and help shape the future of software development. At PureCode, we are utilizing cutting-edge ML tech technologies to automate front-end engineering by generating UI components from text prompts.\n\nThe Ideal Candidate:\n• Proven experience in fast-paced startups, adapting to change and driving innovation\n• Exceptional communication skills, articulating technical concepts clearly\n• Strong problem-solving abilities, proactively identifying and addressing challenges\n• Excellent interpersonal skills, collaborating effectively and contributing to a positive team dynamic\n• Meticulous attention to detail, ensuring high-quality code and documentation\n• Impeccable organization skills, efficiently managing tasks and meeting deadlines\n• Strong people skills, mentoring junior developers and providing constructive feedback\n• Startup mindset and flexibility, eagerly learning new technologies and adapting to evolving needs\n• Expertise in React.js, JavaScript ES6+, HTML5, CSS3, and modern front-end tools\n• Familiarity with Node.js, Express.js, RESTful APIs, and asynchronous data flow\n• Knowledge of testing frameworks and a commitment to clean, maintainable code\n• Experience with version control (Git) and Agile development methodologies\n\nPlease review our company in detail and have an understanding of the product before applying",
    job_is_remote: true,
    job_posted_at_timestamp: 1712090494,
    job_posted_at_datetime_utc: "2024-04-02T20:41:34.000Z",
    job_city: "Austin",
    job_state: "TX",
    job_country: "US",
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react.js+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react.js+developer+in+texas,+usa&htidocid=lo3DOye1BkhPRCYPAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-05-02T00:00:00.000Z",
    job_offer_expiration_timestamp: 1714608000,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 8333,
    job_max_salary: 10000,
    job_salary_currency: "USD",
    job_salary_period: "MONTH",
    job_highlights: {
      Qualifications: [
        "Proven experience in fast-paced startups, adapting to change and driving innovation",
        "Exceptional communication skills, articulating technical concepts clearly",
        "Strong problem-solving abilities, proactively identifying and addressing challenges",
        "Excellent interpersonal skills, collaborating effectively and contributing to a positive team dynamic",
        "Strong people skills, mentoring junior developers and providing constructive feedback",
        "Startup mindset and flexibility, eagerly learning new technologies and adapting to evolving needs",
        "Expertise in React.js, JavaScript ES6+, HTML5, CSS3, and modern front-end tools",
        "Familiarity with Node.js, Express.js, RESTful APIs, and asynchronous data flow",
        "Knowledge of testing frameworks and a commitment to clean, maintainable code",
        "Experience with version control (Git) and Agile development methodologies",
        "Please review our company in detail and have an understanding of the product before applying",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_occupational_categories: ["15-1134.00: Web Developers"],
  },
  {
    job_id: "uYBq29CfsA_QAOaTAAAAAA==",
    employer_name: "Radiantze",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Dice",
    job_employment_type: "CONTRACTOR",
    job_title: "React JS Developer - Plano,TX - Hybrid ( Only Locals )",
    job_apply_link:
      "https://www.dice.com/job-detail/e16b1c80-7190-475d-8f1a-36730bb0a231",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.6015,
    apply_options: [
      {
        publisher: "Dice",
        apply_link:
          "https://www.dice.com/job-detail/e16b1c80-7190-475d-8f1a-36730bb0a231",
        is_direct: true,
      },
      {
        publisher: "React Jobs",
        apply_link: "https://reactjsjob.com/job/2eYbeoIIaMam4lM7hKhe3f9P9Rx",
        is_direct: false,
      },
    ],
    job_description:
      "Position: React Developer\n\nLocation: Plano, TX Only Local\n\nSr Level: 10+ Years\n\nJob Description:\n• Should have more than 8+/10+ Yrs. of relevant experience\n• Should have enough experience on front end technologies & tools, not only on React but also on dependencies related to development\n• Should have hands on experience on cloud services\n• Should have good communication and Leadership skills\n• Should be professional, willing to teach junior engineers\n• Should have design/architecture experience along with exposure to code & design reviews.\n• Should have some knowledge and exposure to API, microservices.\n• Should have experience in developing POCs, shared components, reference implementations.\n\nRegards,\n\nRadiantze Inc",
    job_is_remote: false,
    job_posted_at_timestamp: 1712074152,
    job_posted_at_datetime_utc: "2024-04-02T16:09:12.000Z",
    job_city: "Plano",
    job_state: "TX",
    job_country: "US",
    job_latitude: 33.019844,
    job_longitude: -96.69888,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react.js+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react.js+developer+in+texas,+usa&htidocid=uYBq29CfsA_QAOaTAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-05-03T16:09:12.000Z",
    job_offer_expiration_timestamp: 1714752552,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 120,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: ["React JS"],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Should have more than 8+/10+ Yrs. of relevant experience",
        "Should have enough experience on front end technologies & tools, not only on React but also on dependencies related to development",
        "Should have hands on experience on cloud services",
        "Should have good communication and Leadership skills",
        "Should be professional, willing to teach junior engineers",
        "Should have design/architecture experience along with exposure to code & design reviews",
        "Should have some knowledge and exposure to API, microservices",
        "Should have experience in developing POCs, shared components, reference implementations",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
  {
    job_id: "skiQsDUtHNtA1xpTAAAAAA==",
    employer_name: "Acadia Technologies, Inc.",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Dice",
    job_employment_type: "FULLTIME",
    job_title: "React JS Developer",
    job_apply_link:
      "https://www.dice.com/job-detail/609fcc32-55ed-4141-9e31-e4aa79e313db",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.5999,
    apply_options: [
      {
        publisher: "Dice",
        apply_link:
          "https://www.dice.com/job-detail/609fcc32-55ed-4141-9e31-e4aa79e313db",
        is_direct: true,
      },
    ],
    job_description:
      "1. HTML + CSS 2. JSX 3. JavaScript Fundamentals + ES6 4. Git 5. Node + npm 6. Redux.",
    job_is_remote: false,
    job_posted_at_timestamp: 1712000086,
    job_posted_at_datetime_utc: "2024-04-01T19:34:46.000Z",
    job_city: "Texas City",
    job_state: "TX",
    job_country: "US",
    job_latitude: 29.383844,
    job_longitude: -94.9027,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react.js+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react.js+developer+in+texas,+usa&htidocid=skiQsDUtHNtA1xpTAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-05-02T19:34:46.000Z",
    job_offer_expiration_timestamp: 1714678486,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: ["JavaScript Fundamentals + ES6", "Git"],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 60000,
    job_max_salary: 80000,
    job_salary_currency: "USD",
    job_salary_period: "YEAR",
    job_highlights: {},
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
  {
    job_id: "iNM16pRklYT4IjkcAAAAAA==",
    employer_name: "The Judge Group",
    employer_logo:
      "https://media.licdn.com/dms/image/C4D0BAQGH4WOP34jGTA/company-logo_200_200/0/1630528651657/the_judge_group_logo?e=2147483647&v=beta&t=G6N0sYD0xQi5xsHbdJtZ7ZjJ9tZnyrrXrRcY_opRB8E",
    employer_website: "http://www.judge.com",
    employer_company_type: "Staffing",
    job_publisher: "LinkedIn",
    job_employment_type: "CONTRACTOR",
    job_title: "React.JS Developer (1037791)",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/react-js-developer-1037791-at-the-judge-group-3876475126",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6361,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/react-js-developer-1037791-at-the-judge-group-3876475126",
        is_direct: false,
      },
      {
        publisher: "Dice",
        apply_link:
          "https://www.dice.com/job-detail/da3e4fd0-1d55-4f13-952b-6f655c29b234",
        is_direct: false,
      },
      {
        publisher: "React Jobs",
        apply_link:
          "https://reactjsjob.com/job/2eWUKX5jUguoCWadIyUE869Br58/React.JS%20Developer",
        is_direct: false,
      },
    ],
    job_description:
      "Location: Austin, TX\n\nSalary: $40.00 USD Hourly - $42.00 USD Hourly\n\nDescription: Our client is currently seeking a React.JS Developer\n\nQualifications\n• Bachelor’s degree in computer science, Engineering, or a related field (master’s degree preferred).\n• 3+ years of professional experience in frontend development, with a focus on React.js.\n• Proven experience in React.js is a MUST\n• Proven track record of designing and implementing complex React.js applications from conception to deployment.\n• Strong proficiency in JavaScript/TypeScript, HTML5, CSS3, and related web technologies.\n• Deep understanding of frontend builds tools and package managers (e.g., Webpack, npm).\n• Familiarity with RESTful APIs and asynchronous JavaScript programming.\n• Excellent communication skills, with the ability to effectively articulate technical concepts to both technical and non-technical stakeholders.\n• Ability to thrive in a fast-paced, dynamic environment and adapt to changing priorities.\n\nContact: hrauthan@judge.com\n\nThis job and many more are available through The Judge Group. Find us on the web at www.judge.com",
    job_is_remote: false,
    job_posted_at_timestamp: 1712010729,
    job_posted_at_datetime_utc: "2024-04-01T22:32:09.000Z",
    job_city: "Austin",
    job_state: "TX",
    job_country: "US",
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react.js+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react.js+developer+in+texas,+usa&htidocid=iNM16pRklYT4IjkcAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-05-01T22:32:09.000Z",
    job_offer_expiration_timestamp: 1714602729,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "3+ years of professional experience in frontend development, with a focus on React.js",
        "Proven experience in React.js is a MUST",
        "Proven track record of designing and implementing complex React.js applications from conception to deployment",
        "Strong proficiency in JavaScript/TypeScript, HTML5, CSS3, and related web technologies",
        "Deep understanding of frontend builds tools and package managers (e.g., Webpack, npm)",
        "Familiarity with RESTful APIs and asynchronous JavaScript programming",
        "Excellent communication skills, with the ability to effectively articulate technical concepts to both technical and non-technical stakeholders",
        "Ability to thrive in a fast-paced, dynamic environment and adapt to changing priorities",
      ],
      Benefits: ["Salary: $40.00 USD Hourly - $42.00 USD Hourly"],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "561311",
    job_naics_name: "Employment Placement Agencies",
  },
  {
    job_id: "gwgyiZpU-8o3rb-hAAAAAA==",
    employer_name: "ApTask",
    employer_logo: null,
    employer_website: "http://www.aptask.com",
    employer_company_type: null,
    job_publisher: "Dice",
    job_employment_type: "CONTRACTOR",
    job_title: "Sr. React JS Developer - Plano TX - Locals",
    job_apply_link:
      "https://www.dice.com/job-detail/7f973410-d7aa-4624-84d9-2cc9635bdc15",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.5877,
    apply_options: [
      {
        publisher: "Dice",
        apply_link:
          "https://www.dice.com/job-detail/7f973410-d7aa-4624-84d9-2cc9635bdc15",
        is_direct: true,
      },
      {
        publisher: "React Jobs",
        apply_link:
          "https://reactjsjob.com/job/2eYFleDeYM4dY2cuvPAfgziJBA8/Sr.%20React%20JS%20Developer%20-%20Plano%20TX%20-%20Locals",
        is_direct: false,
      },
    ],
    job_description:
      "Role : Sr. React JS Developer\nLocation : Plano TX - Hybrid\nLong Term Contract\n\n10+ yrs of Experience\n\nTechnical Skills:\n\nWe are seeking a talented React.js Developer to join our dynamic team. The ideal candidate will have a strong passion for technology and the ability to work collaboratively in a fast-paced environment. As a React.js Developer, you will be responsible for developing and implementing user interface components using React.js concepts and workflows. You will also ensure that these components are robust and easy to maintain. Additionally, you will be liaising with the development team to ensure a seamless integration of front-end and back-end technologies.\n\nResponsibilities:\n• Develop new user-facing features using React.js.\n• Build reusable components and front-end libraries for future use.\n• Translate designs and wireframes into high-quality code.\n• Optimize components for maximum performance across a vast array of web-capable devices and browsers.\n• Conduct unit testing, integration testing, and end-to-end testing of the components.\n• Collaborate with the design team to implement user interfaces.\n• Stay up-to-date with the latest trends and best practices in front-end development.\n• Work closely with back-end developers to integrate front-end code with server-side logic.\n• Troubleshoot and debug applications.\n• Participate in code reviews to ensure code quality and consistency.\n\nRahul Joshi\n\nPhone:\n\nEmail:\n\nAddress: 120 Wood Ave South, Suite #300, Iselin, NJ 08830\n\nLinkedIn:",
    job_is_remote: false,
    job_posted_at_timestamp: 1712070603,
    job_posted_at_datetime_utc: "2024-04-02T15:10:03.000Z",
    job_city: "Plano",
    job_state: "TX",
    job_country: "US",
    job_latitude: 33.019844,
    job_longitude: -96.69888,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react.js+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react.js+developer+in+texas,+usa&htidocid=gwgyiZpU-8o3rb-hAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-05-03T15:10:03.000Z",
    job_offer_expiration_timestamp: 1714749003,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 120,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: ["React", "Redux", "HTML", "UI"],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 60,
    job_max_salary: 70,
    job_salary_currency: "USD",
    job_salary_period: "HOUR",
    job_highlights: {
      Qualifications: [
        "10+ yrs of Experience",
        "The ideal candidate will have a strong passion for technology and the ability to work collaboratively in a fast-paced environment",
      ],
      Responsibilities: [
        "As a React.js Developer, you will be responsible for developing and implementing user interface components using React.js concepts and workflows",
        "You will also ensure that these components are robust and easy to maintain",
        "Additionally, you will be liaising with the development team to ensure a seamless integration of front-end and back-end technologies",
        "Develop new user-facing features using React.js",
        "Build reusable components and front-end libraries for future use",
        "Translate designs and wireframes into high-quality code",
        "Optimize components for maximum performance across a vast array of web-capable devices and browsers",
        "Conduct unit testing, integration testing, and end-to-end testing of the components",
        "Collaborate with the design team to implement user interfaces",
        "Stay up-to-date with the latest trends and best practices in front-end development",
        "Work closely with back-end developers to integrate front-end code with server-side logic",
        "Troubleshoot and debug applications",
        "Participate in code reviews to ensure code quality and consistency",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
  {
    job_id: "y96bsyAko4cnBsHAAAAAAA==",
    employer_name: "Valcan IT Inc",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQwBpBM76z7W7g_DjKUsya60I3oBVUduq7nchV&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Dice",
    job_employment_type: "CONTRACTOR",
    job_title: "ReactNative Developer",
    job_apply_link:
      "https://www.dice.com/job-detail/605f59e4-2f0c-43b3-bc0e-9afc5462ebb8",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.5999,
    apply_options: [
      {
        publisher: "Dice",
        apply_link:
          "https://www.dice.com/job-detail/605f59e4-2f0c-43b3-bc0e-9afc5462ebb8",
        is_direct: true,
      },
    ],
    job_description:
      "Role: React Native Developer\nLocation: Houston, TX (Hybrid)\n\nResponsibilities:\nBuild, Develop, maintain and improve existing mobile applications built with React Native\nLeverage native APIs for deep integrations with both platforms.\nDiagnose and fix bugs and performance bottlenecks for performance that feels native.\nWrite clean, well-documented and reusable code\nCollaborate with cross-functional teams to design, develop, and ship new features\nImplement and maintain automated testing and continuous integration/deployment processes\nDebug and troubleshoot issues, and optimize application performance\nPlanning the data and presentation layer for the front end of all applications.\nTransition existing React web apps to React Native.\nStay up-to-date with the latest industry trends and technologies\n\nRequirements:\nPossess at least 5 years of hands-on, end client experience as a React Native Engineer or a similar role.\nFirm grasp of the JavaScript, TypeScript, React its nuances, including ES6+ syntax\nExperience with popular React Native libraries such as Redux, React Navigation, Axios, etc.\nKnowledge of mobile app architecture patterns and best practices\nExperience with native module development in Java/Kotlin for Android and Swift/Objective-C for iOS\nUnderstanding of REST APIs, GraphQL and experience with networking in mobile applications\nAbility to write well-documented, clean Javascript, Typescript code\nRock solid at working with third-party dependencies and debugging dependency conflicts\nStrong debugging and problem-solving skills\nExcellent communication skills",
    job_is_remote: false,
    job_posted_at_timestamp: 1712089580,
    job_posted_at_datetime_utc: "2024-04-02T20:26:20.000Z",
    job_city: "Houston",
    job_state: "TX",
    job_country: "US",
    job_latitude: 29.760427,
    job_longitude: -95.369804,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react.js+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react.js+developer+in+texas,+usa&htidocid=y96bsyAko4cnBsHAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-05-03T20:26:20.000Z",
    job_offer_expiration_timestamp: 1714767980,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: [
      "ES6",
      "GraphQL",
      "Java",
      "JavaScript",
      "Kotlin",
      "Objective - C",
      "React",
      "React Native",
      "React Navigation",
      "Redux",
      "TypeScript",
      "automated testing",
      "communication skills",
      "continuous",
      "continuous integration",
      "debugging",
      "problem - solving",
    ],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Possess at least 5 years of hands-on, end client experience as a React Native Engineer or a similar role",
        "Firm grasp of the JavaScript, TypeScript, React its nuances, including ES6+ syntax",
        "Experience with popular React Native libraries such as Redux, React Navigation, Axios, etc",
        "Knowledge of mobile app architecture patterns and best practices",
        "Experience with native module development in Java/Kotlin for Android and Swift/Objective-C for iOS",
        "Understanding of REST APIs, GraphQL and experience with networking in mobile applications",
        "Ability to write well-documented, clean Javascript, Typescript code",
        "Rock solid at working with third-party dependencies and debugging dependency conflicts",
        "Strong debugging and problem-solving skills",
        "Excellent communication skills",
      ],
      Responsibilities: [
        "Build, Develop, maintain and improve existing mobile applications built with React Native",
        "Leverage native APIs for deep integrations with both platforms",
        "Diagnose and fix bugs and performance bottlenecks for performance that feels native",
        "Write clean, well-documented and reusable code",
        "Collaborate with cross-functional teams to design, develop, and ship new features",
        "Implement and maintain automated testing and continuous integration/deployment processes",
        "Debug and troubleshoot issues, and optimize application performance",
        "Planning the data and presentation layer for the front end of all applications",
        "Stay up-to-date with the latest industry trends and technologies",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    job_id: "8K-mmqGfpS-FrAfnAAAAAA==",
    employer_name: "GlobalLogic",
    employer_logo:
      "https://www.globallogic.com/wp-content/uploads/2021/07/Press-Kit-Logo_GL-Hitachi_Black-1.jpg",
    employer_website: "http://www.globallogic.com",
    employer_company_type: "Computer Services",
    job_publisher: "LinkedIn",
    job_employment_type: "FULLTIME",
    job_title: "Full Stack Engineer (React.JS)",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/full-stack-engineer-react-js-at-globallogic-3878819671",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5606,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/full-stack-engineer-react-js-at-globallogic-3878819671",
        is_direct: false,
      },
    ],
    job_description:
      "Job Description:\n• Looking for a full stack experienced engineer/architect primarily with React/Angular, Java and some SQL DB experience.\n• Anything on top would be great. Looking for someone who is self-motivated, be part of the team and proactive enough to identify areas and guide the team.\n\nRequirements:\n• Strong expertise with ReactJS, or other JavaScript frameworks like Angular, VueJS etc.\n• Good Experience working with API based service layer component using Java.\n• Strong understanding of working with any databases like Oracle/Snowflake/SinglesStore/Teradata & NoSQL databases like Cassandra, Redis.\n• Strong written and oral communication skills.\n• Excellent problem solving and critical thinking with excellent ability to evaluate and apply new technologies in a short time.\n\nEducation:\n• Bachelor's or Master s degree in Computer Science, Computer or Electrical Engineering, Mathematics, or a related field.\n\nWhat We Offer\n\nExciting Projects: Come take your place at the forefront of digital transformation! With clients across all industries and sectors, we offer an opportunity to work on market-defining products using the latest technologies.\n\nCollaborative Environment: You can expand your skills by collaborating with a diverse team of highly talented people in an open, laidback environment — or even abroad in one of our global centers or client facilities!\n\nWork-Life Balance: GlobalLogic prioritizes work-life balance, which is why we offer flexible work schedules and opportunities to work from home.\n\nProfessional Development: We provide continuing education classes, professional certification and training (technical, soft skills, language, and communication skills) to help you realize your professional goals. Being part of a global organization, there are additional learning opportunities through international knowledge exchanges.\n\nExcellent Benefits: We provide our employees with competitive salaries, health and life insurance, short-term and long-term disability insurance, a matched contribution 401K plan, flexible spending accounts, and PTO and holidays.\n\nAbout GlobalLogic: GlobalLogic is a leader in digital engineering. We help brands across the globe design and build innovative products, platforms, and digital experiences for the modern world. By integrating experience design, complex engineering, and data expertise—we help our clients imagine what’s possible, and accelerate their transition into tomorrow’s digital businesses. Headquartered in Silicon Valley, GlobalLogic operates design studios and engineering centers around the world, extending our deep expertise to customers in the automotive, communications, financial services, healthcare and life sciences, manufacturing, media and entertainment, semiconductor, and technology industries. GlobalLogic is a Hitachi Group Company operating under Hitachi, Ltd. (TSE: 6501) which contributes to a sustainable society with a higher quality of life by driving innovation through data and technology as the Social Innovation Business.",
    job_is_remote: false,
    job_posted_at_timestamp: 1712092039,
    job_posted_at_datetime_utc: "2024-04-02T21:07:19.000Z",
    job_city: "Austin",
    job_state: "TX",
    job_country: "US",
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_benefits: [
      "health_insurance",
      "paid_time_off",
      "dental_coverage",
      "retirement_savings",
    ],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react.js+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react.js+developer+in+texas,+usa&htidocid=8K-mmqGfpS-FrAfnAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-05-02T21:07:19.000Z",
    job_offer_expiration_timestamp: 1714684039,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: true,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Strong expertise with ReactJS, or other JavaScript frameworks like Angular, VueJS etc",
        "Good Experience working with API based service layer component using Java",
        "Strong understanding of working with any databases like Oracle/Snowflake/SinglesStore/Teradata & NoSQL databases like Cassandra, Redis",
        "Strong written and oral communication skills",
        "Excellent problem solving and critical thinking with excellent ability to evaluate and apply new technologies in a short time",
        "Bachelor's or Master s degree in Computer Science, Computer or Electrical Engineering, Mathematics, or a related field",
      ],
      Benefits: [
        "Work-Life Balance: GlobalLogic prioritizes work-life balance, which is why we offer flexible work schedules and opportunities to work from home",
        "Excellent Benefits: We provide our employees with competitive salaries, health and life insurance, short-term and long-term disability insurance, a matched contribution 401K plan, flexible spending accounts, and PTO and holidays",
      ],
    },
    job_job_title: "Stack engineer",
    job_posting_language: "en",
    job_onet_soc: "15113300",
    job_onet_job_zone: "4",
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
  },
  {
    job_id: "XELCkmQLJ7jkFuhfAAAAAA==",
    employer_name: "Pinnacle Technical Resources",
    employer_logo:
      "https://content.energage.com/company-images/DA2011/SE11358/SE11358_logo_orig.jpg",
    employer_website: "http://www.pinnacle1.com",
    employer_company_type: null,
    job_publisher: "Indeed",
    job_employment_type: "FULLTIME",
    job_title: "React JS - Advanced",
    job_apply_link: "https://www.indeed.com/viewjob?jk=e85c5582ae61b96c",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.6364,
    apply_options: [
      {
        publisher: "Indeed",
        apply_link: "https://www.indeed.com/viewjob?jk=e85c5582ae61b96c",
        is_direct: true,
      },
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/react-js-advanced-at-pinnacle-group-inc-3878196098",
        is_direct: false,
      },
      {
        publisher: "Dice",
        apply_link:
          "https://www.dice.com/job-detail/e89fc64f-035f-4128-aec9-2339611297ce",
        is_direct: false,
      },
      {
        publisher: "Monster",
        apply_link:
          "https://www.monster.com/job-openings/react-js-advanced-plano-tx--ab49c769-4265-45ea-bd7f-65ee16c23175",
        is_direct: false,
      },
      {
        publisher: "SimplyHired",
        apply_link:
          "https://www.simplyhired.com/job/aTKTPza3aG19ODTK89Qbk4yiLg9bF5nMu3kaNGYu3iloa9l7KRlEaA",
        is_direct: false,
      },
      {
        publisher: "React Jobs",
        apply_link:
          "https://reactjsjob.com/job/2eWUKaxgqfWP9Yiz8KSUNWoSszD/React%20JS%20-%20Advanced",
        is_direct: false,
      },
    ],
    job_description:
      "React JS developer\n\nPlano, Texas\n\n“Must be able to work on W2 without sponsorship.”\n\nJob Description:\n• Expert in React JS and design technique as well as experience working across large environments with multiple operating systems/infrastructure for large-scale programs (e.g., Expert Engineers) starting to be firm-wide resources working on projects across client.\n• Is multi-skilled with expertise across software development lifecycle and toolset\n• May be recognized as a leader in Agile and cultivating teams working in Agile frameworks\n• Sought out as coach for at least one technical skill\n• Strong understanding of techniques such as\n• Continuous Integration, Continuous Delivery, Test Driven Development, Cloud Development, resiliency, security\n• Stays abreast of cutting edge technologies/trends and uses experience to influence application of those technologies/trends to support the business; may give speeches and outside the firm, writes articles\n\nRoles and Responsibilities:\n• Formal training or certification on software engineering concepts and 8+ years of applied experience\n• Hands-on practical experience delivering system design, application development, testing, and operational stability\n• Advanced hands on experience designing solutions in one or more programming language(s): React, Java\n• Experience managing global teams of developers, providing technical support on a day-to-day basis\n• Proven ability to deliver high quality features into production system in an rapid paced, iterative development environment\n• Proficiency in automation and continuous delivery methods\n• Proficient in all aspects of the Software Development Life Cycle\n• Advanced understanding of agile methodologies such as CI/CD, Applicant Resiliency, and Security\n• Demonstrated proficiency in software applications and technical processes within a technical discipline (e.g., cloud, artificial intelligence, machine learning, mobile, etc.)\n• Practical cloud native experience\n\n#LI-MC3\n\nPay Range: $60 - $70\n\nThe specific compensation for this position will be determined by a number of factors, including the scope, complexity and location of the role as well as the cost of labor in the market; the skills, education, training, credentials and experience of the candidate; and other conditions of employment. Our full-time consultants have access to benefits including medical, dental, vision and 401K contributions as well as any other PTO, sick leave, and other benefits mandated by appliable state or localities where you reside or work.\n\n#LI-MC3",
    job_is_remote: false,
    job_posted_at_timestamp: 1712002402,
    job_posted_at_datetime_utc: "2024-04-01T20:13:22.000Z",
    job_city: "Plano",
    job_state: "TX",
    job_country: "US",
    job_latitude: 33.019844,
    job_longitude: -96.69888,
    job_benefits: [
      "health_insurance",
      "retirement_savings",
      "paid_time_off",
      "dental_coverage",
    ],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react.js+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react.js+developer+in+texas,+usa&htidocid=XELCkmQLJ7jkFuhfAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-07-30T21:20:41.000Z",
    job_offer_expiration_timestamp: 1722374441,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 96,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: true,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 60,
    job_max_salary: 70,
    job_salary_currency: "USD",
    job_salary_period: "HOUR",
    job_highlights: {
      Qualifications: [
        "“Must be able to work on W2 without sponsorship.”",
        "Sought out as coach for at least one technical skill",
        "Strong understanding of techniques such as",
        "Formal training or certification on software engineering concepts and 8+ years of applied experience",
        "Hands-on practical experience delivering system design, application development, testing, and operational stability",
        "Advanced hands on experience designing solutions in one or more programming language(s): React, Java",
        "Proficient in all aspects of the Software Development Life Cycle",
        "Advanced understanding of agile methodologies such as CI/CD, Applicant Resiliency, and Security",
        "Demonstrated proficiency in software applications and technical processes within a technical discipline (e.g., cloud, artificial intelligence, machine learning, mobile, etc.)",
        "Practical cloud native experience",
      ],
      Responsibilities: [
        "May be recognized as a leader in Agile and cultivating teams working in Agile frameworks",
        "Continuous Integration, Continuous Delivery, Test Driven Development, Cloud Development, resiliency, security",
        "Stays abreast of cutting edge technologies/trends and uses experience to influence application of those technologies/trends to support the business; may give speeches and outside the firm, writes articles",
        "Proven ability to deliver high quality features into production system in an rapid paced, iterative development environment",
        "Proficiency in automation and continuous delivery methods",
      ],
      Benefits: [
        "Pay Range: $60 - $70",
        "The specific compensation for this position will be determined by a number of factors, including the scope, complexity and location of the role as well as the cost of labor in the market; the skills, education, training, credentials and experience of the candidate; and other conditions of employment",
        "Our full-time consultants have access to benefits including medical, dental, vision and 401K contributions as well as any other PTO, sick leave, and other benefits mandated by appliable state or localities where you reside or work",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
  {
    job_id: "AMuvhLTDjh8r1P52AAAAAA==",
    employer_name: "Mastech Digital",
    employer_logo:
      "https://www.mastechdigital.com/wp-content/uploads/2022/08/Mastech-Logo-1.png",
    employer_website: "http://www.mastechdigital.com",
    employer_company_type: "Computer Services",
    job_publisher: "LinkedIn",
    job_employment_type: "CONTRACTOR",
    job_title: "React Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/react-developer-at-mastech-digital-3877708846",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6427,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/react-developer-at-mastech-digital-3877708846",
        is_direct: false,
      },
      {
        publisher: "Zhorrais.com",
        apply_link:
          "https://zhorrais.com/work/job/react-developer-at-kforce-technology-irving-tx-NmxHL1F1dVh4NzYzbjdvN1J6TjVGV056UWc9PQ==",
        is_direct: false,
      },
      {
        publisher: "Katyj.co.uk",
        apply_link:
          "http://katyj.co.uk/work/job/react-developer-at-kforce-technology-irving-tx-cEdSSDVsWS9jK2JHVGZSVEpDSVJQNUtwb2c9PQ==",
        is_direct: false,
      },
      {
        publisher: "Patrick Keefe",
        apply_link:
          "https://files.patrickkeefe.com/job-library/job/react-developer-at-kforce-technology-irving-tx-QW9YdHFvVkp2LzdZRk15WW9PdzZHSmc1R1E9PQ==",
        is_direct: false,
      },
      {
        publisher: "Xltrak.com",
        apply_link:
          "https://xltrak.com/job-library/job/react-developer-at-kforce-technology-irving-tx-YmlJSVoydHFqdkwvc3l4M3FuNUQraXQzR1E9PQ==",
        is_direct: false,
      },
      {
        publisher: "Brian Humrichouser",
        apply_link:
          "https://brianhumrichouser.com/career/job/react-developer-at-kforce-technology-irving-tx-WFk1U29sMUVsZ3RiMzAzWE1UdnQwRkdZ",
        is_direct: false,
      },
    ],
    job_description:
      "Role: React Developer\n\nLocation: Irving, TX\n\nDuration: 12 months to start with\n\nJob Description:\n\nAs a React developer, you work in a comprehensive JavaScript library known as React. Your responsibilities are to design, develop, and implement this front-end technology for businesses. Your software includes user-facing features that consist of reusable components for future use.\n\nQualifications:\n• 3+ years of experience with frontend frameworks (React Native, Typescript and React)\n• 3+ years of experience building customer facing mobile applications.\n• 3+ years of experience designing and consuming RESTful APIs.\n• 3+ years of experience with Redux\n• Familiarity with native Android in Java and/or Kotlin Stays on the leading edge of software development tools and best practices.\n• Self-directed with a start-up entrepreneur mindset Bachelor’s Degree or higher in Computer Science/Engineering/Math, or relevant experience Bonus Qualifications New Relic (nrql), Logz or any other logger and metrics frameworks Redux Toolkit Experience using gRPC or any other high-performance protocols.\n• Experience with Nx",
    job_is_remote: false,
    job_posted_at_timestamp: 1711986106,
    job_posted_at_datetime_utc: "2024-04-01T15:41:46.000Z",
    job_city: "Irving",
    job_state: "TX",
    job_country: "US",
    job_latitude: 32.81402,
    job_longitude: -96.94889,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react.js+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react.js+developer+in+texas,+usa&htidocid=AMuvhLTDjh8r1P52AAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-05-01T15:41:46.000Z",
    job_offer_expiration_timestamp: 1714578106,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "3+ years of experience with frontend frameworks (React Native, Typescript and React)",
        "3+ years of experience building customer facing mobile applications",
        "3+ years of experience designing and consuming RESTful APIs",
        "3+ years of experience with Redux",
        "Familiarity with native Android in Java and/or Kotlin Stays on the leading edge of software development tools and best practices",
        "Self-directed with a start-up entrepreneur mindset Bachelor’s Degree or higher in Computer Science/Engineering/Math, or relevant experience Bonus Qualifications New Relic (nrql), Logz or any other logger and metrics frameworks Redux Toolkit Experience using gRPC or any other high-performance protocols",
        "Experience with Nx",
      ],
      Responsibilities: [
        "Your responsibilities are to design, develop, and implement this front-end technology for businesses",
        "Your software includes user-facing features that consist of reusable components for future use",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
  },
  {
    job_id: "il_7L-8ltwh9BKXMAAAAAA==",
    employer_name: "GivePulse",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLA4a7wWUBtSB1PHIElG1H41w7i9AwGNRGnWHH&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Built In Austin",
    job_employment_type: "FULLTIME",
    job_title: "React.js Developers (UI)",
    job_apply_link:
      "https://www.builtinaustin.com/job/reactjs-developers-ui/51675",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6793,
    apply_options: [
      {
        publisher: "Built In Austin",
        apply_link:
          "https://www.builtinaustin.com/job/reactjs-developers-ui/51675",
        is_direct: false,
      },
    ],
    job_description:
      "GivePulse is in need to grow our team of engineers and product evangelists. We are specifically looking for Software Engineer to help us scale and continue building civic technology to help address the toughest problems in the community.\n\nEveryone on the team needs to be entrepreneurial, wear a ton of different hats and work in a highly collaborative environment. You will tackle challenging, novel situations every day and will have the opportunity to redefine the volunteer and donation space.\n\nWe have a strong preference for those that live or is willing to move to Austin, TX (we got great breakfast tacos and bbq). We are also willing to make exceptions for candidates outside of Texas but within the US. Note: We also are willing to sponsor H1-B candidates or OPT F-1s. We would love to hear from you and invite qualified candidates to apply at this time via: https://www.givepulse.com/survey/take/mmiIulaqGxuOn9JwFkwB\n\nMore About Us\n\nWe are a social giving platform with a focus to help encourage people to donate and volunteer in the community. We work with over hundreds of thousands of groups, many of which range from your local Animal Center to Ivy Leagues, SMBs to Fortune 500's, Cities to Municipalities, and we engage with millions of active individuals who donate or volunteer.\n\nWe are an Austin based business and are experiencing rapid growth. We are looking for motivated, hungry individuals who want to help us scale further to support millions of volunteers and organizations. There are major opportunities for career advancement for qualified candidates ready to help the company grow and reach our performance goals.\n\nWe at GivePulse are committed to a policy of equal opportunity and non-discrimination on the basis of race, color, national origin, sexual orientation, religion, sex, gender, gender identity, veteran status, age or disability, as protected by law, in all programs and activities and conditions of employment. GivePulse is especially interested in candidates who will take ownership and responsibility to exceed expectations, contribute to open dialogue, build bridges and foster a climate supporting equity, diversity, and belonging. GivePulse is an anti-racist organization. All positions will actively promote diversity, belonging and equity through critical and compassionate communication and strategic outreach efforts to colleagues, partners and institutions (e.g., historically under-represented, first-generation, DACA recipients, LGBTQ community).\n\nRequirements\n• You are a trusted engineer with Computer Science, Computer Engineering or equivalent degree or has relevant work experience.\n• 3+ years of React JS experience (preferred).\n• 2+ years of MySQL and PHP (bonus).\n• Expert Knowledge of CSS, JavaScript and AJAX.\n• Experience with Material UI.\n• Experience with Typescript.\n• Experience Laravel experience a plus.\n• Experience with GIT version control.\n• Ability to create RESTful services.\n• Create unit and integration tests to fully test and regress software.\n• You find a work-around when there is no work-around\n• Great problem solving skills\n• Excellent attention to detail\n• Experience in a fast-paced work environment. You ship quality code quickly\n• A product-first approach to building software. You care about the real world functionality of your programming\n• Other startup experience is a plus\n\nBonuses\n• Likes to rewrite code and make it perform better than O(log n)\n• Likes to participate in tough design and business decisions\n• Cares deeply about social good and civic technology\n\nBenefits\n• Competitive Compensation w/ Fully Covered Medical & Health Benefits\n• Help guide company decisions and direction\n• Be part of the ground floor of a fast growing community focused startup\n• Scale the tech used by hundreds of thousands of groups (nonprofits, cities, businesses etc.,)\n• Scale the usage of a platform to millions more\n• Make an impact on the social good space\n\nPlease apply by submitting your resume and cover letter.\n\nQualified candidates will be invited to interview, do an engineer test, and to meet the team.\n\nhttps://www.givepulse.com/careers\n\n“Be the change that you wish to see in the world.”\n\n― Mahatma Gandhi\n\nAt GivePulse, we provide a fair and equal employment opportunity for all Team Members and candidates regardless of race, color, religion, national origin, gender, pregnancy, sexual orientation, gender identity/expression, age, marital status, disability, or any other legally protected characteristic. GivePulse hires and promotes individuals solely based on qualifications for the position to be filled and business needs.\n\nJob Types: Full-time\n\nSalary: $80,000.00 to $150,000.00/year",
    job_is_remote: true,
    job_posted_at_timestamp: 1710497940,
    job_posted_at_datetime_utc: "2024-03-15T10:19:00.000Z",
    job_city: "Austin",
    job_state: "TX",
    job_country: "US",
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_benefits: ["health_insurance"],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react.js+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react.js+developer+in+texas,+usa&htidocid=il_7L-8ltwh9BKXMAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-04-14T00:00:00.000Z",
    job_offer_expiration_timestamp: 1713052800,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "You are a trusted engineer with Computer Science, Computer Engineering or equivalent degree or has relevant work experience",
        "2+ years of MySQL and PHP (bonus)",
        "Expert Knowledge of CSS, JavaScript and AJAX",
        "Experience with Material UI",
        "Experience with Typescript",
        "Experience with GIT version control",
        "Ability to create RESTful services",
        "Create unit and integration tests to fully test and regress software",
        "You find a work-around when there is no work-around",
        "Great problem solving skills",
        "Excellent attention to detail",
        "Experience in a fast-paced work environment",
        "You ship quality code quickly",
        "A product-first approach to building software",
        "You care about the real world functionality of your programming",
        "Likes to rewrite code and make it perform better than O(log n)",
        "Likes to participate in tough design and business decisions",
      ],
      Benefits: [
        "Competitive Compensation w/ Fully Covered Medical & Health Benefits",
        "Help guide company decisions and direction",
        "Salary: $80,000.00 to $150,000.00/year",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
]

export const JOB_TABLE_HEAD_KEYS = [
  {
    id: 1,
    label: "Job Title",
    name: "job_title",
  },
  {
    id: 2,
    label: "Company",
    name: "employer_name",
  },
  {
    id: 3,
    label: "City",
    name: "job_city",
  },
  {
    id: 4,
    label: "Min. Salary",
    name: "job_min_salary",
  },
  {
    id: 5,
    label: "Max. Salary",
    name: "job_max_salary",
  },
  {
    id: 6,
    label: "Remote (Y/N)",
    name: "job_is_remote",
  },
]
